"""
pdf_generator.py
================
Generates a professional PDF report using ONLY built-in fpdf2 fonts (Helvetica).
Fixed for fpdf2 v2.7+ (output returns bytearray).
"""

from fpdf import FPDF
import io
from PIL import Image
from typing import Dict
from datetime import datetime


class DeepVisionPDF(FPDF):
    """Custom PDF using standard built-in fonts (Helvetica). No TTF files needed."""

    def __init__(self):
        super().__init__("P", "mm", "A4")
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, "DeepVision-AI Analysis Report", align="L")
        self.cell(0, 5, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.line(10, 12, 200, 12)
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by DeepVision-AI | B.Tech CSE(AI) Project - ABESIT Ghaziabad", align="C")


def _sanitize(text: str) -> str:
    """Replace Unicode/Emojis with ASCII equivalents for Helvetica compatibility."""
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        "🤖": "[AI]", "📷": "[REAL]", "✅": "[OK]", "⚠️": "[WARN]",
        "🔍": "[SCAN]", "📝": "[NOTE]", "📄": "[PDF]", "🎯": "[TARGET]",
        "📊": "[STATS]", "🛠️": "[TECH]", "🔬": "[SCI]", "👨‍💻": "[DEV]",
        "🚀": "[GPU]", "💻": "[CPU]", "🏠": "[HOME]", "📜": "[HIST]",
        "ℹ️": "[INFO]", "⚙️": "[SET]", "🚪": "[EXIT]", "🗑️": "[DEL]",
        "—": "--", "•": "-", "→": "->", "←": "<-", "×": "x", "÷": "/",
        "’": "'", "“": '"', "”": '"', "…": "...", "–": "-",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", "replace").decode("latin-1")


def generate_report_pdf(
    image_bytes: bytes,
    image_name: str,
    prediction: Dict,
    exif_result: Dict,
    analysis_text: str,
    user_name: str = "Student User"
) -> bytes:
    pdf = DeepVisionPDF()
    pdf.add_page()

    # --- Cover / Header ---
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(25, 55, 109)
    pdf.cell(0, 15, _sanitize("DeepVision-AI"), new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, _sanitize("AI vs Real Image Detection Report"), new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    pdf.set_draw_color(25, 55, 109)
    pdf.set_line_width(0.8)
    pdf.line(30, pdf.get_y(), 180, pdf.get_y())
    pdf.ln(8)

    # Meta Info
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 6, _sanitize(f"Image: {image_name}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, _sanitize(f"Analyzed by: {user_name}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, _sanitize(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # --- Image Thumbnail ---
    try:
        img = Image.open(io.BytesIO(image_bytes))
        img.thumbnail((160, 160), Image.Resampling.LANCZOS)
        if img.mode in ("RGBA", "LA", "P"): img = img.convert("RGB")
        img_buf = io.BytesIO()
        img.save(img_buf, format="JPEG", quality=85)
        img_buf.seek(0)
        pdf.image(img_buf, x=50, w=110)
        pdf.ln(5)
    except Exception:
        pass

    # --- Verdict Box ---
    verdict = prediction["verdict"]
    confidence = prediction["confidence"]
    ai_pct = prediction["ai_probability"] * 100
    real_pct = prediction["real_probability"] * 100

    if verdict == "AI Generated":
        box_color = (231, 76, 60)
        verdict_tag = "[AI GENERATED]"
    else:
        box_color = (46, 204, 113)
        verdict_tag = "[REAL PHOTOGRAPH]"

    pdf.set_fill_color(*box_color)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    box_h = 18
    pdf.cell(0, box_h, f"  {verdict_tag}  Verdict: {verdict}  ({confidence:.1f}% Confidence)", fill=True, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(4)

    # --- Probability Bars ---
    pdf.set_text_color(40, 40, 40)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Probability Breakdown:", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    def draw_prob_bar(label: str, prob: float, color: tuple):
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        pdf.cell(35, 6, label)
        pdf.set_fill_color(230, 230, 230)
        pdf.cell(130, 6, "", fill=True)
        fill_w = int(130 * prob)
        pdf.set_x(pdf.get_x() - 130)
        pdf.set_fill_color(*color)
        pdf.cell(fill_w, 6, "", fill=True)
        pdf.set_x(pdf.get_x() + 130 - 20)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(40, 40, 40)
        pdf.cell(20, 6, f"{prob*100:.1f}%", align="R", new_x="LMARGIN", new_y="NEXT")

    draw_prob_bar("AI Generated: ", prediction["ai_probability"], (231, 76, 60))
    draw_prob_bar("Real Photograph: ", prediction["real_probability"], (46, 204, 113))
    pdf.ln(6)

    # --- EXIF Metadata Section ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(25, 55, 109)
    pdf.cell(0, 8, "Metadata Forensics (EXIF Analysis)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(25, 55, 109)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    tags = exif_result.get("tags", {})
    flags = exif_result.get("suspicious_flags", [])
    has_exif = exif_result.get("has_exif", False)

    if not has_exif:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(180, 80, 80)
        pdf.multi_cell(0, 5, _sanitize("No EXIF metadata found in the image file. This is common for images downloaded from social media platforms (which strip metadata) and is also typical of AI-generated images. Absence of EXIF alone is not conclusive evidence."))
        pdf.ln(3)
    else:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(40, 40, 40)
        key_fields = [
            ("Camera Make", "Camera Model"),
            ("Lens Model", "Software"),
            ("Date Taken", "Aperture (f-stop)"),
            ("Exposure Time", "ISO"),
            ("Focal Length", "GPS Latitude"),
        ]
        for left, right in key_fields:
            l_val = _sanitize(tags.get(left, "—"))
            r_val = _sanitize(tags.get(right, "—"))
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(45, 5, f"{left}:")
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(55, 5, l_val)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(45, 5, f"{right}:")
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 5, r_val, new_x="LMARGIN", new_y="NEXT")

        pdf.ln(3)

        if flags:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(180, 80, 80)
            pdf.cell(0, 6, _sanitize("Suspicious Indicators Detected:"), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(40, 40, 40)
            for flag in flags:
                pdf.multi_cell(0, 5, _sanitize(f"  - {flag}"))
            pdf.ln(3)
        else:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(46, 160, 80)
            pdf.cell(0, 6, _sanitize("[OK] No obvious metadata anomalies detected."), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(3)

    # --- Descriptive Analysis Text ---
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(25, 55, 109)
    pdf.cell(0, 8, "Detailed Analysis & Explanation", new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(25, 55, 109)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(30, 30, 30)

    paragraphs = analysis_text.split("\n\n")
    for para in paragraphs:
        para = _sanitize(para.strip())
        if not para:
            continue
        if para.startswith("-") or para.startswith("  -"):
            pdf.set_font("Helvetica", "", 9)
            pdf.multi_cell(0, 5, para)
        elif para.endswith(":") and len(para) < 50:
            pdf.set_font("Helvetica", "B", 10)
            pdf.multi_cell(0, 6, para)
        else:
            pdf.set_font("Helvetica", "", 9.5)
            pdf.multi_cell(0, 5, para)
        pdf.ln(2)

    # --- Disclaimer Footer ---
    pdf.ln(5)
    pdf.set_draw_color(180, 180, 180)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    disclaimer = (
        "Disclaimer: This report is generated by an automated AI system for educational and research purposes. "
        "DeepVision-AI uses a deep learning model (ViT-Base) trained on synthetic vs real image datasets, "
        "combined with metadata heuristic analysis. No AI detection system is 100% accurate. False positives and "
        "false negatives are possible, particularly with heavily compressed images, screenshots, advanced generative "
        "models with metadata injection, or unusual camera configurations. This report should not be used as sole "
        "evidence for legal, forensic, or high-stakes decisions."
    )
    pdf.multi_cell(0, 4, _sanitize(disclaimer))

    # --- FIXED RETURN FOR FPDF2 v2.7+ ---
    output = pdf.output(dest="S")
    # fpdf2 >= 2.7.0 returns bytearray; older returns str. Ensure we return bytes.
    if isinstance(output, bytearray):
        return bytes(output)
    if isinstance(output, str):
        return output.encode("latin-1")
    return output


# ---------------------------------------------------------------------------
# Standalone Test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    test_pred = {"ai_probability": 0.12, "real_probability": 0.88, "verdict": "Real Photograph", "confidence": 88.0}
    test_exif = {"has_exif": True, "tags": {"Camera Make": "Canon", "Camera Model": "EOS R6", "Lens Model": "RF 24-70mm", "Software": "Lightroom", "Date Taken": "2024:03:15", "Aperture (f-stop)": "f/2.8", "Exposure Time": "1/250", "ISO": "100", "Focal Length": "35 mm"}, "suspicious_flags": []}
    test_analysis = "Model Assessment:\nThe model classified this as a real photograph.\n\nMetadata Forensics:\n[OK] Camera data present.\n\nCombined Assessment:\nCONSISTENT REAL PHOTOGRAPH."
    dummy_img = Image.new("RGB", (400, 300), color=(200, 50, 50))
    buf = io.BytesIO(); dummy_img.save(buf, format="JPEG")
    pdf_bytes = generate_report_pdf(buf.getvalue(), "test.jpg", test_pred, test_exif, test_analysis, "Test Student")
    with open("test_report.pdf", "wb") as f: f.write(pdf_bytes)
    print("test_report.pdf generated successfully!")
